### ISSUE TITLE
kitty + tmux leads to 'panic: runtime error: index out of range [14] with length 14'

### ISSUE THREAD

**Issue by qcloutier-sonrai** [d-kuro/kubectl-fuzzy#173]
Running any command that invokes the fuzzy selector while in a tmux session on kitty results in a panic. This happens regardless of their configuration settings, I could reproduce it with the defaults. 

Interestingly, it works fine in kitty when tmux isn't being used, and it works fine in tmux when it's not running in kitty. It only appears to break when combining the two.

```
panic: runtime error: index out of range [14] with length 14

goroutine 1 [running]:
github.com/nsf/termbox-go.Close()
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/nsf/termbox-go@v0.0.0-20201124104050-ed494de23a00/api.go:146 +0x4d2
github.com/ktr0731/go-fuzzyfinder.(*termImpl).close(0x3149d08)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/ktr0731/go-fuzzyfinder@v0.3.2/tcell.go:51 +0x25
github.com/ktr0731/go-fuzzyfinder.(*finder).find(0x311a440, 0x21a8200, 0xc000246c18, 0xc0002073e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/ktr0731/go-fuzzyfinder@v0.3.2/fuzzyfinder.go:581 +0xc35
github.com/ktr0731/go-fuzzyfinder.(*finder).Find(0x311a440, 0x21a8200, 0xc000246c18, 0xc0002073e0, 0x0, 0x0, 0x0, 0x0, 0xc000537780, 0x100fa38)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/ktr0731/go-fuzzyfinder@v0.3.2/fuzzyfinder.go:625 +0x7a
github.com/ktr0731/go-fuzzyfinder.Find(...)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/ktr0731/go-fuzzyfinder@v0.3.2/fuzzyfinder.go:621
github.com/d-kuro/kubectl-fuzzy/pkg/fuzzyfinder.Infos(0xc000708a00, 0x20, 0x20, 0xc0005379d8, 0x3, 0x3, 0xcc00266cf50, 0xcc00266d060, 0x100f2db)
        /Users/quinton.cloutier/kubectl-fuzzy/pkg/fuzzyfinder/fuzzyfinder.go:69 +0x267
github.com/d-kuro/kubectl-fuzzy/pkg/cmd.(*LogsOptions).Run(0xc000388340, 0x25f6d00, 0xc000630cc0, 0x0, 0x0)
        /Users/quinton.cloutier/kubectl-fuzzy/pkg/cmd/logs.go:190 +0x3d7
github.com/d-kuro/kubectl-fuzzy/pkg/cmd.NewCmdLogs.func1(0xc0001ab180, 0xc0006340c0, 0x0, 0x1, 0x0, 0x0)
        /Users/quinton.cloutier/kubectl-fuzzy/pkg/cmd/logs.go:50 +0xae
github.com/spf13/cobra.(*Command).execute(0xc0001ab180, 0xc0006340b0, 0x1, 0x1, 0xc0001ab180, 0xc0006340b0)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001aaf00, 0xc000122000, 0xc000181160, 0x2)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/quinton.cloutier/Library/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
main.run(0x25f6670, 0xc000122000, 0x0, 0x0)
        /Users/quinton.cloutier/kubectl-fuzzy/cmd/kubectl-fuzzy/kubectl-fuzzy.go:36 +0x1f7
main.main()
        /Users/quinton.cloutier/kubectl-fuzzy/cmd/kubectl-fuzzy/kubectl-fuzzy.go:21 +0x3d
```

**Comment by d-kuro** [comment]
@qcloutier-sonrai

Thanks for the report!
I haven't thoroughly investigated the cause, but the stack trace suggests that it's probably a bug in [termbox-go](https://github.com/nsf/termbox-go).

https://github.com/nsf/termbox-go/blob/ed494de23a004d7298fbc78a95595388979cd777/api.go#L146

kubectl-fuzzy depends on a library called [go-fuzzyfinder](https://github.com/ktr0731/go-fuzzyfinder) for all of its fuzzy finder implementations.
And the go-fuzzyfinder upstream seems to have a change to replace termbox-go with tcell.

https://github.com/ktr0731/go-fuzzyfinder/pull/55

Your problem may be solved by this Pull Request.
Since go-fuzzyfinder has not been released yet, kubectl-fuzzy will not be able to support it until after the release, but you can use the latest version of go-fuzzyfinder by building kubectl-fuzzy yourself.

```console
$ git clone https://github.com/d-kuro/kubectl-fuzzy.git
$ cd kubectl-fuzzy
$ go get github.com/ktr0731/go-fuzzyfinder@master
$ go mod tidy
$ make install
go install ./cmd/kubectl-fuzzy/ # The built binary will be placed in GOBIN
$ kubectl fuzzy version 
version: v1.8.1 (rev: development) # If you see "rev: development," you've succeeded.
```

When go-fuzzyfinder is released, I'd like to incorporate it into kubectl-fuzzy and release it as soon as possible.

**Comment by qcloutier-sonrai** [comment]
You're right, this is no longer a problem after building with the latest version of go-fuzzyfinder. Thanks!
